### ISSUE TITLE
API: Indication of content/dim variables

### ISSUE THREAD

**Issue by MansMeg** [statisticssweden/PxWeb#1]
Now the pxweb package split the query optimal and download it in chunks. But to do this optimally I need to know what to split on. If I could get info on what is content/dim variables this would be much simpler.

**Comment by likp** [comment]
Hi and sorry for the late reply,

This looks like a bug. According to the specification https://www.scb.se/contentassets/79c32c72783a4f67b202ad3189f921b9/api-beskrivning.pdf each variable should have a attribute called type which specifies the type of the variable (dimension, content or time).

**Comment by MansMeg** [comment]
Ok. I dont remember where I had this problem. I can reopen it if I find it again.
