### ISSUE TITLE
Dots in Pxweb (pxfile-version)

### ISSUE THREAD

**Issue by statgreen** [statisticssweden/PxWeb#109]
**Question**
I have a px-file that has "..." for values that are not ready. But the 3 dots do not show on screen in pxweb2020v1 instead zeroes are shown. I have no older installation to try out. Are the triple dots supposed to show? They do not show in pxwin either - only in pxedit

:-) larsP

**Comment by likp** [comment]
I believe that that it should work with triple dots. If you attach a PX-file I can try it out.

**Comment by likp** [comment]
I just tried to take a PX file and just modify the data part by replacing a value with three dots and I get it in the output in PxWeb
@statgreen does your  PX file contain a override of how ... should be displayed?

![triple_dot](https://user-images.githubusercontent.com/29275976/115363877-210b1080-a1c3-11eb-8916-4701ffd016e9.png)

**Comment by statgreen** [comment]
strange - I think it is unchanged from out of the box - and nothing added in file except "..." in DATA

![image](https://user-images.githubusercontent.com/14994906/115394706-cfae5180-a1c1-11eb-8fa3-0e493fa863bc.png)

**Comment by statgreen** [comment]
[BEXCALC.zip](https://github.com/statisticssweden/PxWeb/files/6343542/BEXCALC.zip)

**Comment by LarsLap** [comment]
Sorry, Petros my mistake. It is good. It is when aggregating the zeroes is shown. 

http://betabank20.stat.gl/sq/4bb1090f-b6da-4c89-bde1-21b8e2862b6c

**Comment by likp** [comment]
Ok, I will close the issue then.
