### ISSUE TITLE
Uppgrade PxWeb and its components to .NET framework 4.8

### ISSUE THREAD

**Issue by likp** [statisticssweden/PxWeb#159]
.NET framework 4.6.1 is going out of support on April 26 2022.

https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework

**Comment by oyessb** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/runtime/4.6.1-4.8#runtime

**Comment by likp** [comment]
This has been done
