### ISSUE TITLE
Rewrite abandoned?

### ISSUE THREAD

**Issue by dpriskorn** [statisticssweden/PxWeb#210]
The branches seem stale... Has the rewrite been abandoned?
https://github.com/statisticssweden/PxWeb/blob/0124191d3a4c583fd2aeadacfdd245ce6754d249/README.md?plain=1#L5

**Comment by likp** [comment]
All components except PCAxis.Serach has been converted to .NET standard and moved to their own repositories. So the comment is no longer valid
