### ISSUE TITLE
Language manager - Obsnote label

### ISSUE THREAD

**Issue by igorstat-si** [statisticssweden/PxWeb#235]
Translation in slovenian language, on Pxweb main interface the translation is not shown properly; also not in english: Explanation.

sentence name="CtrlFootnoteObsnoteLabel" value="Pojasnilo: "

![image](https://user-images.githubusercontent.com/105707002/168762756-a0a935eb-99ae-47eb-9f85-468d19986736.png)
![image](https://user-images.githubusercontent.com/105707002/168762841-1a5cce1e-528b-45c3-a714-61da9cc44206.png)

**Comment by likp** [comment]
It is a bug in PxWeb 2021 v1 that was fixed with https://github.com/statisticssweden/PxWeb/pull/186/files
