### ISSUE TITLE
Footnotes in wrong language

### ISSUE THREAD

**Issue by AsaArrhen** [statisticssweden/PxWeb#238]
Below the table there is a footnote with English text in Swedish database.

**Comment by likp** [comment]
@AsaArrhen could you add information about which table it is so that we can reproduce the table.

**Comment by AsaArrhen** [comment]
@likp https://www.statistikdatabasen.scb.se/sq/125193 is one example

**Comment by likp** [comment]
The problem is in Statistics Swedens database.

**Comment by AsaArrhen** [comment]
Har skapat en PBI
