### ISSUE TITLE
i18n support?

### ISSUE THREAD

**Issue by johnfelipe** [statisticssweden/PxWeb#258]
i want contribute for translate to es, fr and it if you have strings in js, json, xml or pot file

**Comment by likp** [comment]
That really sounds nice. All sentences are are stored for each language in a xml-file located under the Resources\Languages folder for PxWeb (https://github.com/statisticssweden/PxWeb/tree/master/PXWeb/Resources/Languages). It should be one file for each language. 

You could either use the built in tool in PxWeb or just add you translation to existing och new xml-file if that language is not translated.

**Comment by johnfelipe** [comment]
Wich lang is native, main language for review and re create es, de, fr and
it.

**Comment by likp** [comment]
The default language it English which i located in https://github.com/statisticssweden/PxWeb/blob/master/PXWeb/Resources/Languages/pxlang.xml

**Comment by likp** [comment]
I just sent you a mail (to you address registered at GitHub) containing instructions and a compiled version.

**Comment by johnfelipe** [comment]
Perfecto in a few hours I will begin with es
But I need pxweb installed in my IIS windows or like your memo or
cheatsheet or markdown readme file teach me
