### ISSUE TITLE
Can u help me for install in ubuntu 20 from scratch or if u have docker?

### ISSUE THREAD

**Issue by johnfelipe** [statisticssweden/PxWeb#261]
Can u help me for install in ubuntu 20 from scratch or if u have docker?

**Comment by johnfelipe** [comment]
anyone?

**Comment by likp** [comment]
@johnfelipe PxWeb is currently written in .NET framework and unfortunately only runs under Windows.

**Comment by johnfelipe** [comment]
Then for windows...
