### ISSUE TITLE
pls send me installation steps for ubuntu 20

### ISSUE THREAD

**Issue by johnfelipe** [statisticssweden/PxWeb#263]
Installation
If you are looking for a compiled version of the source, ready to install in your environment. Then please send a mail to [pc-axis@scb.se](mailto:pc-axis@scb.se?subject=Access%20to%20download%20portal) and you will receive credentials to Statistics Sweden’s download portal where you can download a complied version together with instructions.

i already send to your email. this request but nothing happend

**Comment by johnfelipe** [comment]
anyone?
r u there?
may be in vacations period?

**Comment by johnfelipe** [comment]
anyone?

**Comment by likp** [comment]
Our administrator for the pc-axis@scb.se i on vacation and will be back august 15.

**Comment by johnfelipe** [comment]
And only that person can share compiled version and instructions for deploy?

**Comment by johnfelipe** [comment]
i know this app havent support for linux
