### ISSUE TITLE
Google Analytics not registering user data with the 2021 version of PxWeb

### ISSUE THREAD

**Issue by pokkeko** [statisticssweden/PxWeb#264]
Google Analytics has been installed on the site using the tag manager, and the setup was seemingly successful as the tool is working with prior versions of PxWeb. The issue is affecting both Universal Analytics and GA4. Has anyone had similar issues, or has Analytics working with the current version of PxWeb?

**Comment by likp** [comment]
I have not experience this but my guess is that you will get more relevant answers if you post it to the google group.
