### ISSUE TITLE
Compact view does not show at first time visit

### ISSUE THREAD

**Issue by AsaArrhen** [statisticssweden/PxWeb#339]
**Describe the bug**
The compact view is suppposed to be the default view when you visit PxWeb the first time but now it shows the list view and you have to press the Listview button twice to change the setting

**Expected behavior**
The compact view is shown when visiting PxWeb for the first time and the button says List view

**Actual behavior**
You come to PxWeb for the first time and you See the List view and the Button List view is shown. 
When you presss the List view button the button changes to Compact and the view is still List view
Press the button again and the view changes to compact view

PxWeb 2022v1

**Comment by statisticamd** [comment]
The same problem, please let me know if you solve this problem. Thanks.

**Comment by jerikso** [comment]
The bug is due to a cookie not being created on the first load.
Fixed in #473.
