### ISSUE TITLE
Links show with html-code in file

### ISSUE THREAD

**Issue by AsaArrhen** [statisticssweden/PxWeb#363]
Contact: Olof Gustavsson Uppsala kommun

One example at Statistics Sweden: Download a file to excel [Arbetsmarknadsstatus efter region, kön, ålder och födelseregion. Preliminär statistik. Månad 2020M01 - 2022M09. PxWeb (scb.se)](https://www.statistikdatabasen.scb.se/pxweb/sv/ssd/START__AM__AM0210__AM0210A/ArbStatusM/). 
a.	In this table there is a link to the footnote that looks good in html but gets the problem when downloaded to excel. 

The text in excel is <a href='https://www.scb.se/AM0210#_Dokumentation'>kvalitetsdeklaration </a> 

It would be nice if excel interprets this as a link.

**Comment by likp** [comment]
[Functionality Uppsala kommun.xlsx](https://github.com/statisticssweden/PxWeb/files/10839419/Functionality.Uppsala.kommun.xlsx)

**Comment by AsaArrhen** [comment]
I denna tabell finns en länk i fotnoten som ser bra ut i web/html vy men får samma problem när en excel laddas ner. Texten som visas i excel är <a href='https://www.scb.se/AM0210#_Dokumentation'>kvalitetsdeklaration </a> det vore ju fint att tolka om detta till en klickbar länk även i excel.

**Comment by AsaArrhen** [comment]
Dubblett med #237 Stänger denna
