### ISSUE TITLE
Metadata returns creation day instead of updated in API JSON-format 

### ISSUE THREAD

**Issue by pokkeko** [statisticssweden/PxWeb#387]
**Describe the bug**
PxWeb API returns creation day value instead of updated date in JSON- and JSON-STAT(2) format.
Is it possible for the user to change the metadata values returned by the API?

**To Reproduce**
1. Go to 'https://statdb.luke.fi:443/PxWeb/sq/1ea2394e-bd78-40c4-afaa-c6aa80cc5866/'
2. Take the API-query from this table and change the response format to "json" or "json-stat2"
3. In the response metadata section the "updated" value is the "creation day" value.

**Expected behavior**
the "updated" value 

**Actual behavior**
 the "creation day" value.

**Screenshots**

**Environment information**
 - OS: [windows 10]
 - Browser [all]
 - Version 
 - Device: [e.g. laptop, etc]

**Additional context**

From Postman:
    ],
    "metadata": [
        {
            "updated": "2014-08-26T08:00:00Z",
            "label": "Total fish production in Finland by region, type and year",
            "source": "Natural Resources Institute Finland, Total fish production"
        }
    ]
}

**Comment by likp** [comment]
Yes, it it looks like a bug. If a content variable is not defined LastUpdated is at table level. But JSON, JSON-STAT and JSON-STAT2 do not look there istead it fall backs on Creation Time.
