### ISSUE TITLE
Big gap in footnotes

### ISSUE THREAD

**Issue by AsaArrhen** [statisticssweden/PxWeb#49]
Each time we save the page with english-swedish translations all translations get an extra line break in each box. 
See mail pc-axis mailbox HLV Tandhälsa ålder

Example: You want to change name of your database. Go to languageManager and finf PxWeb 2020 v1. Write Åsas Database Swedish (Sweden) Save Make another change and Save. Then the words you wrote instead of PxWeb 2020 v1 has diasappeared since they have moved down in the box and can't be seen.

All changes are moved so you can't see any of them.

**Comment by likp** [comment]
@AsaArrhen could you include the details from the mailbox to this issue.

**Comment by likp** [comment]
@AsaArrhen I believe that you can jyst drag and drop them e.g. the comment or in the issue description in "edit-mode"

**Comment by AsaArrhen** [comment]
Såg att det finns en lösning här på Github mot detta. Kommer i nästa version: https://github.com/statisticssweden/PxWeb/pull/41

**Comment by MikaelNordberg** [comment]
ControlRenderingCompatibiltyVersion has now been set to 4.5 in the PxWeb Master branch. This solves the problem in the Language Manager tool in the PxWeb Administration tool.
