### ISSUE TITLE
Force conforming to API documentation

### ISSUE THREAD

**Issue by MansMeg** [statisticssweden/PxWeb#5]
Statistics Norway previously added "h" in their PXWEB API. That really hard  to spot and made it difficult toi handle since it wasn't a part of the API documentation.

**Comment by MikaelNordberg** [comment]
Hi,
Documentation about the "h" in the API will be present in the next release of PxWeb. 
Thank you for this feedback.

**Comment by MikaelNordberg** [comment]
The API documentation has been updated and can be reached at:
https://www.scb.se/en/services/oppna-data/api-for-the-statistical-database/
