### ISSUE TITLE
[QUERY] json-stat2 documentation

### ISSUE THREAD

**Issue by lorenzobruni** [statisticssweden/PxWeb#54]
Myself and @statgreen have noticed that the online PDF documentation of the **PxAPI** https://www.scb.se/en/services/oppna-data/api-for-the-statistical-database/ is not referring to the `json-stat2` support.

Can you please add it to the PDF documentation for cross-reference?
Also, it might be good to inform that the generic `json-stat` format returns the **1.x** version rather than the current version 2.x
 
Thank you!

**Comment by lorenzobruni** [comment]
FYI, we are updating the [PxStat](https://github.com/CSOIreland/PxStat) API adapter (aka PxAPIv1) to support both `json-stat` and `json.stat2` formats.
See this Issue https://github.com/CSOIreland/PxStat/issues/250

Cheers

**Comment by statgreen** [comment]
Let me know, when you want me to test

☺ LarsP

Fra: Lorenzo Bruni [mailto:notifications@github.com]
Sendt: 19. oktober 2020 19:54
Til: statisticssweden/PxWeb
Cc: Lars Pedersen; Mention
Emne: Re: [statisticssweden/PxWeb] [QUERY] json-stat2 documentation (#54)


FYI, we are updating the PxStat<https://github.com/CSOIreland/PxStat> API adapter (aka PxAPIv1) to support both json-stat and json.stat2 formats.
See this Issue CSOIreland/PxStat#250<https://github.com/CSOIreland/PxStat/issues/250>

Cheers

**Comment by lorenzobruni** [comment]
Will do very soon 👍

**Comment by lorenzobruni** [comment]
@statgreen / @likp 
I don't want to go OT here, so I opened this one were to test the `json-stat` and `json-stat2` formats in the **PxAPIv1** adapter: 
[[HELP] Testing API adapter for PxAPIv1 interface #258](https://github.com/CSOIreland/PxStat/issues/258)

...get back with good news ;-)

**Comment by MikaelNordberg** [comment]
The API documentation has been updated and can be reached at:
https://www.scb.se/en/services/oppna-data/api-for-the-statistical-database/
