### ISSUE TITLE
Wrong type of file when I download Excel

### ISSUE THREAD

**Issue by petroslikidis** [statisticssweden/PxWeb#55]
**Describe the bug**
When i download an Exel file i only get an xml file

**To Reproduce**
1. Visit www.statistikdatbasen.scb.se
2. clock on any table
3. Select any value
4. In presentation view click the excel button

**Expected behavior**
To get an xlsx file

**Actual behavior**
Is got a xml file

**Comment by likp** [comment]
Demo issue form the Px ref meetning
