### ISSUE TITLE
Language manager - "English" changes wrong txt-file

### ISSUE THREAD

**Issue by AsaArrhen** [statisticssweden/PxWeb#56]
**Language manager change wrong file**

1. Go to 'Language manager in the administration tool.' 
2. Click on English'
3. Scroll down to PXWeb 2020v1 and change the text.'
4. Reset language. 
5. The file Pxlang.en changes and damages the language manager. It ought to be the file pxlang.xml that changes.

 - Browser [Edge]

**Comment by MikaelNordberg** [comment]
An english language file (pxlang.en.xml) that can be edited by the Language manager tool has been added to PxWeb
