### ISSUE TITLE
Aggregations in sub-folders need iis restart to take effect

### ISSUE THREAD

**Issue by statgreen** [statisticssweden/PxWeb#57]
**Describe the bug**
Aggregations in sub-folders need iis restart to take effect

**To Reproduce**
add a new subfolder to aggregations-folder
add vs + agg files

start admin UI
update database
use reset all

**Expected behavior**
Expect aggregations to be updated and ok

**Actual behavior**
It does not work

**Additional context**
It works after restart of IIS

**Comment by likp** [comment]
I just checked the code and it does an async reloading of the aggregations so it might not reload them immediately. @statgreen could you try to do an reset and wait 5 min to see if it picked up the changes.

**Comment by statgreen** [comment]
Changes are not picked up till iisrestart. I waited 10 min, before restart

☺ LarsP

Fra: likp [mailto:notifications@github.com]
Sendt: 16. november 2020 09:22
Til: statisticssweden/PxWeb
Cc: Lars Pedersen; Mention
Emne: Re: [statisticssweden/PxWeb] Aggregations in sub-folders need iis restart to take effect (#57)


I just checked the code and it does an async reloading of the aggregations so it might not reload them immediately. @statgreen<https://github.com/statgreen> could you try to do an reset and wait 5 min to see if it picked up the changes.

**Comment by likp** [comment]
It looks like ReloadGroupings is not loading aggregations files from subfolders which LoadGrouoings does. See https://github.com/statisticssweden/PxWeb/blob/3c83e020e21ac8e7b6cda41dc271b087310906ad/PCAxis.PX.Core/Grouping/GroupRegistry.vb#L341

**Comment by statgreen** [comment]
Also I now notice, after splitting aggregations in 2 subfolders and no agg/vs in topfolder (aggregations) - that they don't take effect - even after iis restart. When moved to topfolder - they take effect
