### ISSUE TITLE
PxAPI pivoting output by any Dimension

### ISSUE THREAD

**Issue by lorenzobruni** [statisticssweden/PxWeb#59]
FYI, we have extended the **API Adapters** in [PxStat](https://github.com/CSOIreland/PxStat), including the **PxAPI Version 1** to accept an optional parameter to allow pivoting the output by any Dimension.

In this way the user can download or query the API by requesting the data pivoted by a dimension.
Of course this apply only to CSV and XLSX (Excel) formats as JSON-stat has a flat format.

Perhaps this enhancement may be interesting for you to implement as well on your side.

Here is a live example (https://data.cso.ie/table/WPM24) where you can experiment this feature.
I'm available if you wish more details, cheers.
![image](https://user-images.githubusercontent.com/53212047/99919785-6fe97280-2d17-11eb-97a7-42a4b5ec2b87.png)

**Comment by likp** [comment]
We are not investing more time in the old API could be a feature in the 2.0 version.
