### ISSUE TITLE
JSON schemas for returned objects

### ISSUE THREAD

**Issue by MansMeg** [statisticssweden/PxWeb#6]
It would be good to see exactly what one could expect from the JSON objects that are now returned.

**Comment by likp** [comment]
Hi and sorry for the late reply,

It a good idea. We might be able to to this for the metadata queries. Let me check with some others that might already have done this.

Please note that we have done so already for the version 2.0 of the API (https://github.com/statisticssweden/PxApiSpecs/blob/master/PxApi-2.0.json).

**Comment by MansMeg** [comment]
Thats excellent! Thanks!

**Comment by likp** [comment]
Will be handled in PxWeb API 2.0.
