### ISSUE TITLE
bug when changing language after selecting aggregation

### ISSUE THREAD

**Issue by statgreen** [statisticssweden/PxWeb#63]
**Describe the bug**
bug when changing language after selecting aggregation

**To Reproduce**
1. Go to 'https://bank.stat.gl/beest1'
2. Select any classification for 'Age' and all values for age and gender
3. Click continue
4. See table on screen
5. Change language

**Expected behavior**
as without selecting aggregation. language should change - also for table

**Actual behavior**
only interface change language, table is still in English

**Environment information**
 - OS: Win
 - Browser chrome
 - Device: [PC]

**Comment by pokkeko** [comment]
We have the same problem in Natural Resources Institute Finland statistical database (https://statdb.luke.fi/PXWeb/pxweb/en/LUKE/).
Also the localization does not work with the aggregated saved queries (?lang=en).

**Comment by likp** [comment]
I believe that this is a known limitation due to the fact that we do not know which aggregation to apply in the other language selected since there is no linkage between the aggration files.
