### ISSUE TITLE
Convert excel file to a px file using the latest compiled version

### ISSUE THREAD

**Issue by nbabiker** [statisticssweden/PxWeb#72]
dear all,
I am new user to px web we are trying to use Pxweb for dissmenting data on renewable energy statistics at our organization.

I have been struggling to use PX-edit to convert excel files to PX files, in order to data the files to a database on PX web with no luck so far. I was wondering if there some guidance somewhere on how to convert excel/csv files into PX-files ? Your assistance is
highly appreciated.

Nazik 
IRENA

**Comment by likp** [comment]
Hi @nbabiker, we have a google mail group that is a good forum to ask general questions about the tools around PxWeb. We have the people from Statistics Finland that has developed PxEdit activly on the mail group. They will probably be able to help you.

I you would like to join please send a email to pc-axis@scb.se and we will send you an invite to join.
