### ISSUE TITLE
The skiplink doesn’t work

### ISSUE THREAD

**Issue by MikaelNordberg** [statisticssweden/PxWeb#76]
When navigating PxWeb using TAB a skip-link is displayed "Jump to main content".
This link doesn´t work. The anchor position that it points to probably doesn’t exist on the page.

**Comment by likp** [comment]
Discovered in PxWeb 2020 v2

Works only on the selection page.

**Comment by JohannesFinsveen** [comment]
Seems to be working on the presentation page as well.
