### ISSUE TITLE
copy button in save your query

### ISSUE THREAD

**Issue by statgreen** [statisticssweden/PxWeb#92]
I wish for a copy-button as it is a little too tricky to mark link to saved query - when the query string exceeds the length of the box

![miss_copy_button](https://user-images.githubusercontent.com/14994906/109278190-020d8500-77f7-11eb-8451-4f30e677c60f.jpg)

**Comment by PerIngeVaaje** [comment]
We are looking at it now

**Comment by PerIngeVaaje** [comment]
@statgreen Look at this proposal https://www.qa.ssb.no/en/statbank/table/07459/

**Comment by likp** [comment]
I have tried it out in Chrome and Edge in Windows, Chrome on Android and Safari, Firefox and Chrome on iOS and it works as I would expect. Great work!
